:loud_sound: add sound interface
epitech-mirroring/ArcadeShared pull request #26
Opened 2024-04-04 15:47 UTC by Antoinegtir

Add some features to handle Sound in SFML:

- function to get the path where the sound is stored (using .wav exension)
- function in order to set the path of this sound
- fonction to repeat or not the sound

2024-04-04 15:56 UTC, RenardFute requested changes

2024-04-04 15:56 UTC, RenardFute commented on sound/ISound.hpp
> +#include "../utils/ICoordinate.hpp"
useless can you remove it ?

2024-04-04 16:01 UTC, RenardFute approved these changes

2024-04-06 15:08 UTC, aimeric44uwu approved these changes

2024-11-03 17:22 UTC, merged